<%@ Page Title="Stations by Line" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="LineStation.aspx.cs" Inherits="CloverEVA.LineStatus" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>
    <h3>Configuración de Estaciones por Linea</h3>
    <div class="jumbotron">
        <div>
            <table class="table"><tr>
                <td style="text-align:right"><asp:Label ID="Label1" runat="server" Text="Linea :"></asp:Label></td>
                <td style="align-items:center">
                    <asp:DropDownList ID="DropDownList1" runat="server"></asp:DropDownList>
                </td>
                <td><asp:Button ID="btLoad" runat="server" Text="Cargar" CssClass="btn btn-primary btn-sm" /></td>
            </tr></table>
        </div>
        <div>
            <asp:GridView ID="gwData" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True">
                <Columns>
                    <asp:BoundField DataField="planta" Visible="false" />
                    <asp:BoundField DataField="linea" Visible="false" />
                    <asp:BoundField DataField="maquina" HeaderText="Estación" />
                    <asp:BoundField DataField="operacion" HeaderText="Operación" />
                    <asp:BoundField DataField="tiempo" HeaderText="Duración" />
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>